<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Idioma;

class IdiomasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Idioma::truncate();
        $idiomas = [
            ['idioma' => 'ESPAÑOL', 'iso'=> 'ES', 'usuario_id' => 1],
            ['idioma' => 'INGLÉS', 'iso'=> 'EN', 'usuario_id' => 1],
            ['idioma' => 'AZERÍ', 'iso'=> 'AZ', 'usuario_id' => 1],
            ['idioma' => 'AFRIKAANS', 'iso'=> 'AF', 'usuario_id' => 1],
            ['idioma' => 'ALBANÉS', 'iso'=> 'SQ', 'usuario_id' => 1],
            ['idioma' => 'ALEMÁN', 'iso'=> 'DE', 'usuario_id' => 1],
            ['idioma' => 'ALSACIANO', 'iso'=> 'ALS', 'usuario_id' => 1],
            ['idioma' => 'AMÁRICO', 'iso'=> 'AM', 'usuario_id' => 1],
            ['idioma' => 'ANGLOSAJÓN', 'iso'=> 'ANG', 'usuario_id' => 1],
            ['idioma' => 'ÁRABE', 'iso'=> 'AR', 'usuario_id' => 1],
            ['idioma' => 'ARAGONÉS', 'iso'=> 'AN', 'usuario_id' => 1],
            ['idioma' => 'ARMENIO', 'iso'=> 'HY', 'usuario_id' => 1],
            ['idioma' => 'ASTURIANO', 'iso'=> 'AST', 'usuario_id' => 1],
            ['idioma' => 'AYMARA', 'iso'=> 'AY', 'usuario_id' => 1],
            ['idioma' => 'BAJO SAJÓN', 'iso'=> 'NDS', 'usuario_id' => 1],
            ['idioma' => 'BENGALÍ', 'iso'=> 'BN', 'usuario_id' => 1],
            ['idioma' => 'BIELORRUSO', 'iso'=> 'BE', 'usuario_id' => 1],
            ['idioma' => 'BIRMANO', 'iso'=> 'MY', 'usuario_id' => 1],
            ['idioma' => 'BOSNIO', 'iso'=> 'BS', 'usuario_id' => 1],
            ['idioma' => 'BRETÓN', 'iso'=> 'BR', 'usuario_id' => 1],
            ['idioma' => 'BÚLGARO', 'iso'=> 'BG', 'usuario_id' => 1],
            ['idioma' => 'CANARÉS', 'iso'=> 'KN', 'usuario_id' => 1],
            ['idioma' => 'CATALÁN', 'iso'=> 'CA', 'usuario_id' => 1],
            ['idioma' => 'CHAMORRO', 'iso'=> 'CH', 'usuario_id' => 1],
            ['idioma' => 'CHECO', 'iso'=> 'CS', 'usuario_id' => 1],
            ['idioma' => 'CHEROQUI', 'iso'=> 'CHR', 'usuario_id' => 1],
            ['idioma' => 'CHINO MANDARÍN', 'iso'=> 'ZH', 'usuario_id' => 1],
            ['idioma' => 'COREANO', 'iso'=> 'KO', 'usuario_id' => 1],
            ['idioma' => 'CORSO', 'iso'=> 'CO', 'usuario_id' => 1],
            ['idioma' => 'CROATA', 'iso'=> 'HR', 'usuario_id' => 1],
            ['idioma' => 'CURDO', 'iso'=> 'KU', 'usuario_id' => 1],
            ['idioma' => 'DANÉS', 'iso'=> 'DA', 'usuario_id' => 1],
            ['idioma' => 'ESLOVACO', 'iso'=> 'SK', 'usuario_id' => 1],
            ['idioma' => 'ESLOVENO', 'iso'=> 'SL', 'usuario_id' => 1],
            ['idioma' => 'ESPERANTO', 'iso'=> 'EO', 'usuario_id' => 1],
            ['idioma' => 'ESTONIO', 'iso'=> 'ET', 'usuario_id' => 1],
            ['idioma' => 'EUSKERA', 'iso'=> 'EU', 'usuario_id' => 1],
            ['idioma' => 'FEROÉS', 'iso'=> 'FO', 'usuario_id' => 1],
            ['idioma' => 'FIYIANO', 'iso'=> 'FJ', 'usuario_id' => 1],
            ['idioma' => 'FINLANDÉS', 'iso'=> 'FI', 'usuario_id' => 1],
            ['idioma' => 'FRANCÉS', 'iso'=> 'FR', 'usuario_id' => 1],
            ['idioma' => 'FRISÓN', 'iso'=> 'FY', 'usuario_id' => 1],
            ['idioma' => 'GALÉS', 'iso'=> 'CY', 'usuario_id' => 1],
            ['idioma' => 'GALLEGO', 'iso'=> 'GL', 'usuario_id' => 1],
            ['idioma' => 'GEORGIANO', 'iso'=> 'KA', 'usuario_id' => 1],
            ['idioma' => 'GRIEGO MODERNO', 'iso'=> 'EL', 'usuario_id' => 1],
            ['idioma' => 'GUARANÍ', 'iso'=> 'GN', 'usuario_id' => 1],
            ['idioma' => 'GUJARATÍ', 'iso'=> 'GU', 'usuario_id' => 1],
            ['idioma' => 'HEBREO ISRAELÍ', 'iso'=> 'HE', 'usuario_id' => 1],
            ['idioma' => 'HINDI', 'iso'=> 'HI', 'usuario_id' => 1],
            ['idioma' => 'HOLANDÉS', 'iso'=> 'NL', 'usuario_id' => 1],
            ['idioma' => 'HÚNGARO', 'iso'=> 'HU', 'usuario_id' => 1],
            ['idioma' => 'IDO', 'iso'=> 'IO', 'usuario_id' => 1],
            ['idioma' => 'IGBO', 'iso'=> 'IG', 'usuario_id' => 1],
            ['idioma' => 'INDONESIO', 'iso'=> 'ID', 'usuario_id' => 1],
            ['idioma' => 'INGLÉS SIMPLIFICADO', 'iso'=> 'PLE', 'usuario_id' => 1],
            ['idioma' => 'INTERLINGUA', 'iso'=> 'IA', 'usuario_id' => 1],
            ['idioma' => 'IRLANDÉS', 'iso'=> 'GA', 'usuario_id' => 1],
            ['idioma' => 'ISLANDÉS', 'iso'=> 'IS', 'usuario_id' => 1],
            ['idioma' => 'ITALIANO', 'iso'=> 'IT', 'usuario_id' => 1],
            ['idioma' => 'JAPONÉS', 'iso'=> 'JA', 'usuario_id' => 1],
            ['idioma' => 'JAVANÉS', 'iso'=> 'JV', 'usuario_id' => 1],
            ['idioma' => 'KAZAKO', 'iso'=> 'KK', 'usuario_id' => 1],
            ['idioma' => 'LAOSIANO', 'iso'=> 'LO', 'usuario_id' => 1],
            ['idioma' => 'LATÍN', 'iso'=> 'LA', 'usuario_id' => 1],
            ['idioma' => 'LETÓN', 'iso'=> 'LV', 'usuario_id' => 1],
            ['idioma' => 'LINGALA', 'iso'=> 'LN', 'usuario_id' => 1],
            ['idioma' => 'LITUANO', 'iso'=> 'LT', 'usuario_id' => 1],
            ['idioma' => 'LUXEMBURGUÉS', 'iso'=> 'LB', 'usuario_id' => 1],
            ['idioma' => 'MACEDONIO', 'iso'=> 'MK', 'usuario_id' => 1],
            ['idioma' => 'MALABAR', 'iso'=> 'ML', 'usuario_id' => 1],
            ['idioma' => 'MALAYO', 'iso'=> 'MS', 'usuario_id' => 1],
            ['idioma' => 'MALGACHE', 'iso'=> 'MG', 'usuario_id' => 1],
            ['idioma' => 'MALTÉS', 'iso'=> 'MT', 'usuario_id' => 1],
            ['idioma' => 'MANÉS', 'iso'=> 'GV', 'usuario_id' => 1],
            ['idioma' => 'MAORÍ', 'iso'=> 'MI', 'usuario_id' => 1],
            ['idioma' => 'MARATI', 'iso'=> 'MR', 'usuario_id' => 1],
            ['idioma' => 'MOLDAVO', 'iso'=> 'MO', 'usuario_id' => 1],
            ['idioma' => 'MONGOL', 'iso'=> 'MN', 'usuario_id' => 1],
            ['idioma' => 'NÁHUATL', 'iso'=> 'NAH', 'usuario_id' => 1],
            ['idioma' => 'NAURUANO', 'iso'=> 'NA', 'usuario_id' => 1],
            ['idioma' => 'NORUEGO', 'iso'=> 'NO', 'usuario_id' => 1],
            ['idioma' => 'OCCITANO', 'iso'=> 'OC', 'usuario_id' => 1],
            ['idioma' => 'PAPIAMENTO', 'iso'=> 'PAP', 'usuario_id' => 1],
            ['idioma' => 'PERSA MODERNO', 'iso'=> 'FA', 'usuario_id' => 1],
            ['idioma' => 'POLACO', 'iso'=> 'PL', 'usuario_id' => 1],
            ['idioma' => 'PORTUGUÉS', 'iso'=> 'PT', 'usuario_id' => 1],
            ['idioma' => 'PUNJABÍ', 'iso'=> 'PA', 'usuario_id' => 1],
            ['idioma' => 'QUECHUA', 'iso'=> 'QU', 'usuario_id' => 1],
            ['idioma' => 'QUIRGUIZ', 'iso'=> 'KY', 'usuario_id' => 1],
            ['idioma' => 'ROMANCHE', 'iso'=> 'RM', 'usuario_id' => 1],
            ['idioma' => 'RUMANO', 'iso'=> 'RO', 'usuario_id' => 1],
            ['idioma' => 'RUSO', 'iso'=> 'RU', 'usuario_id' => 1],
            ['idioma' => 'SARDO', 'iso'=> 'SC', 'usuario_id' => 1],
            ['idioma' => 'SERBIO', 'iso'=> 'SR', 'usuario_id' => 1],
            ['idioma' => 'SESOTHO', 'iso'=> 'ST', 'usuario_id' => 1],
            ['idioma' => 'SICILIANO', 'iso'=> 'SCN', 'usuario_id' => 1],
            ['idioma' => 'SOMALÍ', 'iso'=> 'SO', 'usuario_id' => 1],
            ['idioma' => 'SUECO', 'iso'=> 'SV', 'usuario_id' => 1],
            ['idioma' => 'SWAHILI', 'iso'=> 'SW', 'usuario_id' => 1],
            ['idioma' => 'TAGALO', 'iso'=> 'TL', 'usuario_id' => 1],
            ['idioma' => 'TAILANDÉS', 'iso'=> 'TH', 'usuario_id' => 1],
            ['idioma' => 'TAMIL', 'iso'=> 'TA', 'usuario_id' => 1],
            ['idioma' => 'TÁRTARO', 'iso'=> 'TT', 'usuario_id' => 1],
            ['idioma' => 'TÁRTARO DE CRIMEA', 'iso'=> 'CRH', 'usuario_id' => 1],
            ['idioma' => 'TEGULÚ', 'iso'=> 'TE', 'usuario_id' => 1],
            ['idioma' => 'TIBETANO', 'iso'=> 'BO', 'usuario_id' => 1],
            ['idioma' => 'TURCO', 'iso'=> 'TR', 'usuario_id' => 1],
            ['idioma' => 'TURCOMANO', 'iso'=> 'TK', 'usuario_id' => 1],
            ['idioma' => 'UCRANIANO', 'iso'=> 'UK', 'usuario_id' => 1],
            ['idioma' => 'URDU', 'iso'=> 'UR', 'usuario_id' => 1],
            ['idioma' => 'UZBEKO', 'iso'=> 'UZ', 'usuario_id' => 1],
            ['idioma' => 'VALÓN', 'iso'=> 'WA', 'usuario_id' => 1],
            ['idioma' => 'VIETNAMITA', 'iso'=> 'VI', 'usuario_id' => 1],
            ['idioma' => 'VOLAPUK', 'iso'=> 'VO', 'usuario_id' => 1],
            ['idioma' => 'XHOSA', 'iso'=> 'XH', 'usuario_id' => 1],
            ['idioma' => 'YIDISH', 'iso'=> 'YI', 'usuario_id' => 1],
            ['idioma' => 'YORUBA', 'iso'=> 'YO', 'usuario_id' => 1],
            ['idioma' => 'ZULÚ', 'iso'=> 'ZU', 'usuario_id' => 1]
        ];
        foreach($idiomas as $idioma) {
            Idioma::create($idioma);
        }
    }
}
