<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Indice;

class IndicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Indice::truncate();
        $indices = [
            ['indice' =>'NO PERTENECE A NINGÚN INDICE','usuario_id'=>1],
            ['indice' =>'A B C POL SCI','usuario_id'=>1],
            ['indice' =>'ABSTRACTS IN ANTROPOLOGY','usuario_id'=>1],
            ['indice' =>'ABSTRACTS OF MYCOLOGY','usuario_id'=>1],
            ['indice' =>'ABSTRACTSON HYGIENEANDCOMMUNICABLEDISEASES','usuario_id'=>1],
            ['indice' =>'ABSTRACTSON TROPICAL AGRICULTURE','usuario_id'=>1],
            ['indice' =>'ACADEMIC SEARCH COMPLETE','usuario_id'=>1],
            ['indice' =>'AGRICOLA','usuario_id'=>1],
            ['indice' =>'AGRICULTURALAND ENVIRONMETALBIOTECHONOLOGYABSTRACTS','usuario_id'=>1],
            ['indice' =>'AGRINDEX','usuario_id'=>1],
            ['indice' =>'AGRIS','usuario_id'=>1],
            ['indice' =>'AGROBASE','usuario_id'=>1],
            ['indice' =>'AGROFORESTRY ABSTRACTS','usuario_id'=>1],
            ['indice' =>'AIDS ABSTRACTS','usuario_id'=>1],
            ['indice' =>'AMERICA HISTORY AND LIFE','usuario_id'=>1],
            ['indice' =>'ANIMAL BEHAVIORABSTRACTS','usuario_id'=>1],
            ['indice' =>'ANIMALBREEDINGABSTRACTS','usuario_id'=>1],
            ['indice' =>'ANTHOROPOLOGICALLITERATURE','usuario_id'=>1],
            ['indice' =>'API AMERICANPETROLEUMCOMPANY','usuario_id'=>1],
            ['indice' =>'APPLIEDMECHANICSREVIEWS','usuario_id'=>1],
            ['indice' =>'AQUATICSCIENCESANDFISHERIESABSTRACTS(ASFA)','usuario_id'=>1],
            ['indice' =>'ARCHITECTURALPUBLICATIONSINDEX','usuario_id'=>1],
            ['indice' =>'ART & HUMANITIESCITATION INDEX','usuario_id'=>1],
            ['indice' =>'BASE','usuario_id'=>1],
            ['indice' =>'BIBLAT','usuario_id'=>1],
            ['indice' =>'BIBLIOTECAVIRTUALDE CLASO','usuario_id'=>1],
            ['indice' =>'BIOLOGICALASBTRACTS','usuario_id'=>1],
            ['indice' =>'BIOTECHNOLOGY ABSTRACTS','usuario_id'=>1],
            ['indice' =>'BUSINESS SOURCE COMPLETE','usuario_id'=>1],
            ['indice' =>'CAB ABSTRACTS','usuario_id'=>1],
            ['indice' =>'CHEMICAL ABSTRACTS','usuario_id'=>1],
            ['indice' =>'CIRCCLASIFICACION INTEGRADA DE REVISTASCIENTIFICA','usuario_id'=>1],
            ['indice' =>'CLASE','usuario_id'=>1],
            ['indice' =>'COMPENDEX','usuario_id'=>1],
            ['indice' =>'COMPLUDOC','usuario_id'=>1],
            ['indice' =>'CURRENT CONTENTS','usuario_id'=>1],
            ['indice' =>'DAIRYSCIENCEABSTRACTS','usuario_id'=>1],
            ['indice' =>'DAREDATABANK','usuario_id'=>1],
            ['indice' =>'DIALNET','usuario_id'=>1],
            ['indice' =>'DIRECTORY OF OPEN ACCESS JOUNARLS(DOAJ)','usuario_id'=>1],
            ['indice' =>'EBSCO EDUCATION SOURCE','usuario_id'=>1],
            ['indice' =>'ECOLOGICAL ABSTRACTS','usuario_id'=>1],
            ['indice' =>'ECONLIT','usuario_id'=>1],
            ['indice' =>'ELECTRONIC JOURNALS LIBRARY','usuario_id'=>1],
            ['indice' =>'EMBASE EXCERPTA MEDICA','usuario_id'=>1],
            ['indice' =>'EMERGINCSOURCESCITATIONINDEXESCI','usuario_id'=>1],
            ['indice' =>'ENGINEERINGINDEX','usuario_id'=>1],
            ['indice' =>'ENTOMOLOGY ABSTRACTS','usuario_id'=>1],
            ['indice' =>'E-PSYCHE','usuario_id'=>1],
            ['indice' =>'ERIC','usuario_id'=>1],
            ['indice' =>'ERIH PLUS','usuario_id'=>1],
            ['indice' =>'EZB ELECTRONIC JOUNALS LIBRARY','usuario_id'=>1],
            ['indice' =>'FIELDCROPABSTRACTS','usuario_id'=>1],
            ['indice' =>'FLUID ABSTRACTS','usuario_id'=>1],
            ['indice' =>'FLUIDEX','usuario_id'=>1],
            ['indice' =>'FOOD SCIENCEANDTECHNOLOGY ASTRACTS','usuario_id'=>1],
            ['indice' =>'FORESTRY ABSTRACTS','usuario_id'=>1],
            ['indice' =>'FREE MEDICAL JOURNALS','usuario_id'=>1],
            ['indice' =>'FUENTE ACADEMICA','usuario_id'=>1],
            ['indice' =>'GEOARCHIVE','usuario_id'=>1],
            ['indice' =>'GEOBASE','usuario_id'=>1],
            ['indice' =>'GEODADOS','usuario_id'=>1],
            ['indice' =>'GEOGRAPHICAL ABSTRACTS: HUMAN GEOGRAPHY','usuario_id'=>1],
            ['indice' =>'GEOLOGICAL ABSTRACTS','usuario_id'=>1],
            ['indice' =>'GEOREF','usuario_id'=>1],
            ['indice' =>'GEOSCIENCE DOCUMENTATION','usuario_id'=>1],
            ['indice' =>'GRASSLANDS AND FORAGE ABSTRACTS','usuario_id'=>1],
            ['indice' =>'HAPIHISPANIC AMERICAN PERIODICALS INDEX','usuario_id'=>1],
            ['indice' =>'HLA','usuario_id'=>1],
            ['indice' =>'HORTICULTURALABSTRACTS','usuario_id'=>1],
            ['indice' =>'IDA (INTERNATIONAL DEVELOPMENT ABSTRACTS','usuario_id'=>1],
            ['indice' =>'IHEAL','usuario_id'=>1],
            ['indice' =>'IMBIOMED','usuario_id'=>1],
            ['indice' =>'IMLA INDEX MEDICUS LATINO-AMERICANO','usuario_id'=>1],
            ['indice' =>'INDEX MEDICUS','usuario_id'=>1],
            ['indice' =>'INDEXCOPERNICUSINTERNATIONAL','usuario_id'=>1],
            ['indice' =>'INDEXVETERINARIUS','usuario_id'=>1],
            ['indice' =>'INFOBILA','usuario_id'=>1],
            ['indice' =>'INFORME ACADÉMICO','usuario_id'=>1],
            ['indice' =>'INIS ATOMINDEX','usuario_id'=>1],
            ['indice' =>'INSPEC THE INSTITUTION OF ELECTRICAL ENGINEERS','usuario_id'=>1],
            ['indice' =>'INTERNATIONALBIBLIOGRAPHYOF THESOCIAL SCIENCES','usuario_id'=>1],
            ['indice' =>'IRESIE','usuario_id'=>1],
            ['indice' =>'LATAM STUDIES','usuario_id'=>1],
            ['indice' =>'LATINDEX CATALOGO','usuario_id'=>1],
            ['indice' =>'LATINDEX- DIRECTORIO','usuario_id'=>1],
            ['indice' =>'LIBRARY LITERATURE FULL TEXT','usuario_id'=>1],
            ['indice' =>'LILACS','usuario_id'=>1],
            ['indice' =>'LINGUISTICS ABSTRACTS','usuario_id'=>1],
            ['indice' =>'LINGUISTICS AND LANGUAGE BEHAVIOR ABSTRACTS','usuario_id'=>1],
            ['indice' =>'MATERIALS RESEARCH DATABASE','usuario_id'=>1],
            ['indice' =>'MATH SCI','usuario_id'=>1],
            ['indice' =>'MATHEMATICALREVIEWS','usuario_id'=>1],
            ['indice' =>'MEDIGRAPHIC','usuario_id'=>1],
            ['indice' =>'MEDLINE','usuario_id'=>1],
            ['indice' =>'METADEX','usuario_id'=>1],
            ['indice' =>'METALS ABSTRACTS INDEX','usuario_id'=>1],
            ['indice' =>'MIAR','usuario_id'=>1],
            ['indice' =>'MINERALOGICALABSTRACTS','usuario_id'=>1],
            ['indice' =>'NUTRITION ABSTRACTS AND REVIEWSSERIE AHUMAN AND EXPERIMENTAL','usuario_id'=>1],
            ['indice' =>'OEI-CREDI','usuario_id'=>1],
            ['indice' =>'P A I S INTERNATIONALPUBLIC AFFAIRS INFORMATION SERVICE','usuario_id'=>1],
            ['indice' =>'PERIODICA','usuario_id'=>1],
            ['indice' =>'PETROLEUM ABSTRACTS','usuario_id'=>1],
            ['indice' =>'PHILOSOPHERS INDEX','usuario_id'=>1],
            ['indice' =>'PLANT BREEDING ABSTRATS','usuario_id'=>1],
            ['indice' =>'POLITICAL SCIENCE COMPLETE','usuario_id'=>1],
            ['indice' =>'PROQUETSNATURAL SCIENCE JOURNALD','usuario_id'=>1],
            ['indice' =>'PUBLINDEX','usuario_id'=>1],
            ['indice' =>'RED ALYC','usuario_id'=>1],
            ['indice' =>'REDIB','usuario_id'=>1],
            ['indice' =>'REDINSE','usuario_id'=>1],
            ['indice' =>'REFERATIVNYI ZHURNAL','usuario_id'=>1],
            ['indice' =>'RESEARCHPAPERSINECONOMICSREPEC','usuario_id'=>1],
            ['indice' =>'REVENCY','usuario_id'=>1],
            ['indice' =>'REVIEW OF AGRICULTURAL ENTOMOLOGY','usuario_id'=>1],
            ['indice' =>'REVISTASSABER ULA','usuario_id'=>1],
            ['indice' =>'RICE ABSTRACTS','usuario_id'=>1],
            ['indice' =>'ROAD','usuario_id'=>1],
            ['indice' =>'SCIELO','usuario_id'=>1],
            ['indice' =>'SCIENCE CITATIÓN INDEXEXPANDED','usuario_id'=>1],
            ['indice' =>'SCOPUS','usuario_id'=>1],
            ['indice' =>'SEED ABSTRACTS','usuario_id'=>1],
            ['indice' =>'SHERPA/ROMEO','usuario_id'=>1],
            ['indice' =>'SOCIAL SCIENCESCITATION INDEX','usuario_id'=>1],
            ['indice' =>'SOCIAL SCISEARCH','usuario_id'=>1],
            ['indice' =>'SOCIOLOGICALABSTRACTS','usuario_id'=>1],
            ['indice' =>'SPELEOLOGICALABSTRACTS','usuario_id'=>1],
            ['indice' =>'TROPICAL ABSTRACTS','usuario_id'=>1],
            ['indice' =>'TROPICAL DISEASES BULLETIN','usuario_id'=>1],
            ['indice' =>'ULRICHS','usuario_id'=>1],
            ['indice' =>'VETERINARY BULLETIN','usuario_id'=>1],
            ['indice' =>'VETERINARY SCIENCE','usuario_id'=>1],
            ['indice' =>'WEED ABSTRACTS','usuario_id'=>1],
            ['indice' =>'ZOOLOGICALRECORD','usuario_id'=>1],
            ['indice' =>'OPEN JOURNAL SYSTEM (OJS)','usuario_id'=>1],
            ['indice' =>'LATINDEX','usuario_id'=>1],
            ['indice' =>'REBIUN','usuario_id'=>1],
            ['indice' =>'DOAJ','usuario_id'=>1],
            ['indice' =>'REVENCYT','usuario_id'=>1],
        ];
        foreach($indices as $indice) {
            Indice::create($indice);
        }        
    }
}
