<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RevistasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('revistas')->delete();
        
        \DB::table('revistas')->insert(array (
            0 => 
            array (
                'id' => 2,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'CIENCIA REVISTA ACADEMIA MEXíCANA DE CIENCIA',
                'correo_revista' => 'revista@correo.com',
                'editorial_id' => 5,
                'periodicidad_id' => 8,
                'formato_id' => 1,
                'estado_id' => 8,
                'ciudad_id' => 143,
                'nombres_editor' => 'LUIS',
                'apellidos_editor' => 'GóMEZ',
                'correo_editor' => 'editor@correo.com',
                'deposito_legal_impreso' => 'dsfsdf',
                'deposito_legal_digital' => '258',
                'issn_impreso' => 'DSFSDF',
                'issn_digital' => '123',
                'url' => '',
                'anio_inicial' => 1970,
                'direccion' => 'SDF DF SDF SDFSDF SDF DF ',
                'telefono' => '02124627811',
                'resumen' => 'ASDASD',
                'portada' => '[{"name":"portadas\\/ciencia_psicopatia_gc6901qn.jpg","usrName":"ciencia_psicopatia.jpg","size":227230,"type":"image\\/jpeg","thumbnail":"portadas\\/thciencia_psicopatia_cf00qy3l.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4426,"searchStr":"ciencia_psicopatia.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            1 => 
            array (
                'id' => 3,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'NEUROCIRUGIA',
                'correo_revista' => 'revista@correo.com',
                'editorial_id' => 5,
                'periodicidad_id' => 7,
                'formato_id' => 3,
                'estado_id' => 22,
                'ciudad_id' => 449,
                'nombres_editor' => 'LUIS',
                'apellidos_editor' => 'GóMEZ',
                'correo_editor' => 'editor@correo.com',
                'deposito_legal_impreso' => 'rtertrt',
                'deposito_legal_digital' => 'yutyur',
                'issn_impreso' => 'QWES',
                'issn_digital' => 'HFFYTT',
                'url' => 'https://revistanaturista.com',
                'anio_inicial' => 1970,
                'direccion' => 'TY RY TRY YRT YRTY RTY TRY',
                'telefono' => '02124627811',
                'resumen' => 'ADFDSFSADF',
                'portada' => '[{"name":"portadas\\/neurocirugia_ijxe60e4.jpg","usrName":"neurocirugia.jpg","size":113228,"type":"image\\/jpeg","thumbnail":"portadas\\/thneurocirugia_lq21h1ea.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3212,"searchStr":"neurocirugia.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            2 => 
            array (
                'id' => 4,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'REVISTA GEOGRáFICA VENEZOLANA',
                'correo_revista' => 'revista@correo.com',
                'editorial_id' => 12,
                'periodicidad_id' => 6,
                'formato_id' => 2,
                'estado_id' => 13,
                'ciudad_id' => 239,
                'nombres_editor' => 'LUIS',
                'apellidos_editor' => 'GóMEZ',
                'correo_editor' => 'editor@correo.com',
                'deposito_legal_impreso' => '123',
                'deposito_legal_digital' => 'trterterwt',
                'issn_impreso' => '123',
                'issn_digital' => 'WQEQWEQW',
                'url' => 'http://revista.com',
                'anio_inicial' => 1970,
                'direccion' => 'WQE WQEWQ E WQE WQEWQ EQWE W',
                'telefono' => '02124627811',
                'resumen' => 'QWEQWEQWEQWE',
                'portada' => '[{"name":"portadas\\/revista_geografica_hhmwuie5.jpg","usrName":"revista_geografica.jpg","size":9083,"type":"image\\/jpeg","thumbnail":"portadas\\/threvista_geografica_4d76ysfe.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3113,"searchStr":"revista_geografica.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            3 => 
            array (
                'id' => 1,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'CIENCIAS DE LA EDUCACIóN',
                'correo_revista' => 'revista@correo.com',
                'editorial_id' => 5,
                'periodicidad_id' => 3,
                'formato_id' => 3,
                'estado_id' => 15,
                'ciudad_id' => 303,
                'nombres_editor' => 'PEDRO',
                'apellidos_editor' => 'PéREZ',
                'correo_editor' => 'editor@correo.com',
                'deposito_legal_impreso' => 'dsfsdfd f',
                'deposito_legal_digital' => 'ioyttrr',
                'issn_impreso' => 'QWEQW E',
                'issn_digital' => 'DFSFSFD',
                'url' => 'http://revista.com',
                'anio_inicial' => 1970,
                'direccion' => 'SDFSDF FSDF D FDF D',
                'telefono' => '02124627811',
                'resumen' => 'R ERER ER  WERER',
                'portada' => '[{"name":"portadas\\/ciencias_educacion_20rhi4p3.jpg","usrName":"ciencias_educacion.jpg","size":14713,"type":"image\\/jpeg","thumbnail":"portadas\\/thciencias_educacion_ycthlh1b.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4628,"searchStr":"ciencias_educacion.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            4 => 
            array (
                'id' => 10,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACTA BIOCLíNICA',
                'correo_revista' => 'saberula@gmail.com',
                'editorial_id' => 20,
                'periodicidad_id' => 8,
                'formato_id' => 1,
                'estado_id' => 13,
                'ciudad_id' => 245,
                'nombres_editor' => 'GLADYS',
                'apellidos_editor' => 'VELAZCO',
                'correo_editor' => 'gvelazcoula@gmail.com',
                'deposito_legal_impreso' => 'ppi201102me3815',
                'deposito_legal_digital' => '123',
                'issn_impreso' => '2244-813',
                'issn_digital' => '456',
                'url' => 'http://erevistas.saber.ula.ve/index.php/actabiocli',
                'anio_inicial' => 2011,
                'direccion' => 'CENTRO DE INVESTIGACIONES ODONTOLóGICAS
FACULTAD DE ODONTOLOGíA
EDIF. ADJUNTO AL RECTORADO',
                'telefono' => '2742402343',
                'resumen' => 'ACTA BIOCLINICA ES UN ORGANO DE DIVULGACIóN CIENTíFICA ARBITRADO DEL áREA BIOMéDICA QUE BáSICAMENTE TIENE COMO FINALIDAD LA DIFUSIóN PROMOCIóN Y APOYO A LAS INVESTIGACIONES, ASí COMO, A LAS ACTIVIDADES ACADéMICAS Y CIENTíFICAS EN LOS CAMPOS DE LA ODONTOLOGíA, MEDICINA, BIOINGENIERíA, BIOMATERIALES, Y TODAS LAS CIENCIAS BIOMéDICAS. ',
                'portada' => '[{"name":"portadas\\/IMGActaBiocl__nica4-_1__qgesr24v.jpg","usrName":"IMGActaBioclínica4-_1_.jpg","size":124930,"type":"image\\/jpeg","thumbnail":"portadas\\/thIMGActaBiocl__nica4-_1__kwj91ltv.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4730,"searchStr":"IMGActaBioclínica4-_1_.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            5 => 
            array (
                'id' => 7,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACADEMIA',
                'correo_revista' => 'racademia@ula.ve',
                'editorial_id' => 20,
                'periodicidad_id' => 6,
                'formato_id' => 2,
                'estado_id' => 20,
                'ciudad_id' => 440,
                'nombres_editor' => 'ALEXIS',
                'apellidos_editor' => 'BERMúDEZ',
                'correo_editor' => 'racademia@ula.ve',
                'deposito_legal_impreso' => '456',
                'deposito_legal_digital' => '456',
                'issn_impreso' => '456',
                'issn_digital' => '2244 - 8',
                'url' => 'http://erevistas.saber.ula.ve/index.php/academia/a',
                'anio_inicial' => 2001,
                'direccion' => 'NúCLEO UNIVERSITARIO ',
                'telefono' => '02742524192',
                'resumen' => 'ACADEMIA ES UNA REVISTA QUE TIENE COMO OBJETIVO, PUBLICAR ARTíCULOS ORIGINALES, REVISIONES, COMUNICACIONES CORTA Y RESEñAS DE LIBROS, SOBRE TEMAS DE CUALQUIER ESPECIALIDAD, PERTENECIENTES A CIENCIAS HUMANAS, CIENCIAS NATURALES, CIENCIAS DE LA SALUD Y AVANCES TECNOLóGICOS.',
            'portada' => '[{"name":"portadas\\/Academia (1) (1)_68si1rop.jpg","usrName":"Academia (1) (1).jpg","size":111092,"type":"image\\/jpeg","thumbnail":"portadas\\/thAcademia (1) (1)_obhef0ge.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4180,"searchStr":"Academia (1) (1).jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            6 => 
            array (
                'id' => 9,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACTUAL        ',
                'correo_revista' => 'revistaactual1968@gmail.c',
                'editorial_id' => 20,
                'periodicidad_id' => 6,
                'formato_id' => 3,
                'estado_id' => 13,
                'ciudad_id' => 245,
                'nombres_editor' => 'DIANAYRA',
                'apellidos_editor' => 'VALERO',
                'correo_editor' => 'divamo78@gmail.com',
                'deposito_legal_impreso' => '789',
                'deposito_legal_digital' => '789',
                'issn_impreso' => '1315-858',
                'issn_digital' => '789',
                'url' => 'http://erevistas.saber.ula.ve/index.php/actualdivu',
                'anio_inicial' => 1968,
                'direccion' => 'DIRECCIóN DE CULTURA, AVENIDA TULIO FEBRES CORDERO, EDIFICIO ADMINISTRATIVO DE LA UNIVERSIDAD DE LOS ANDES, 4TO PISO.',
                'telefono' => '2742524192',
                'resumen' => 'REVISTA ACTUAL, TIENE CASI CUARENTA Y CINCO AñOS DE PERMANENCIA CON SUS ALTIBAJOS Y SUS LUCHAS PARA GANARSE LA CONTINUIDAD Y TRASCENDENCIA DENTRO DEL ARTE Y LA CULTURA. GRANDES ESTUDIOSOS DE LAS LETRAS Y PENSADORES HAN SIDO SUS EDITORES, DESDE SALVADOR GARMENDIA, SU FUNDADOR, PASANDO POR EDMUNDO ARAY, ARNALDO ACOSTA BELLO, LUBIO CARDOZO, VíCTOR BRAVO,  LUIS RICARDO DáVILA, GREGORY ZAMBRANO HASTA EL PRESENTE EDITOR MAURICIO NAVIA A; POR LA QUE LA REVISTA ACTUAL TIENE BIEN MERECIDO SU LUGAR DENTRO DE LAS PUBLICACIONES PERIóDICAS.',
            'portada' => '[{"name":"portadas\\/Actual (2)_b3ryuxtz.jpg","usrName":"Actual (2).jpg","size":90063,"type":"image\\/jpeg","thumbnail":"portadas\\/thActual (2)_082ex4fh.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3682,"searchStr":"Actual (2).jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACTIVIDAD FíSICA Y CIENCIAS',
                'correo_revista' => 'yaritza.cova@upel.edu.ve',
                'editorial_id' => 21,
                'periodicidad_id' => 8,
                'formato_id' => 3,
                'estado_id' => 4,
                'ciudad_id' => 64,
                'nombres_editor' => 'GRISELL',
                'apellidos_editor' => 'BOLíVAR',
                'correo_editor' => '',
                'deposito_legal_impreso' => 'ppi200902ar3122',
                'deposito_legal_digital' => '987',
                'issn_impreso' => '789',
                'issn_digital' => '2244 731',
                'url' => 'https://revistas.upel.edu.ve/index.php/actividadfi',
                'anio_inicial' => 2009,
                'direccion' => ' AV. LAS DELICIAS, ANTIGUO PARQUE DE FERIAS. EDIFICIO ADMINISTRATIVO, 2DO PISO.',
                'telefono' => '0416648842',
                'resumen' => 'LA REVISTA ELECTRóNICA ARBITRADA ACTIVIDAD FíSICA Y CIENCIAS, ADEMáS DE SUS NúMEROS REGULARES DE PUBLICACIóN SEMESTRAL, PUBLICARá HASTA DOS NúMEROS MONOGRáFICOS EXTRAORDINARIOS AL AñO, SOBRE TEMAS ESPECíFICOS DE ACTUALIDAD Y RELEVANCIA SIGNIFICATIVA, VINCULADOS CON LAS CIENCIAS APLICADAS A LA ACTIVIDAD FíSICA Y A OTRAS áREAS DE LA REVISTA COMO EDUCACIóN FíSICA, DEPORTE, RECREACIóN Y DANZA.',
                'portada' => '[{"name":"portadas\\/Actividad F__sica_hszsqvvm.jpg","usrName":"Actividad Física.jpg","size":88773,"type":"image\\/jpeg","thumbnail":"portadas\\/thActividad F__sica_zmqetw68.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3703,"searchStr":"Actividad Física.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            8 => 
            array (
                'id' => 12,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACTA CIENTíFICA',
                'correo_revista' => 'saberucvrevistas@gmail.co',
                'editorial_id' => 23,
                'periodicidad_id' => 8,
                'formato_id' => 3,
                'estado_id' => 24,
                'ciudad_id' => 149,
                'nombres_editor' => 'MARíA FÁTIMA ',
                'apellidos_editor' => 'GARCÉS',
                'correo_editor' => 'mariafatimagarces@hotmail',
                'deposito_legal_impreso' => 'pp 199202df899',
                'deposito_legal_digital' => '654',
                'issn_impreso' => '987',
                'issn_digital' => ' 1315-17',
                'url' => 'https://www.svbe.org/acta-cientifica/',
                'anio_inicial' => 1992,
                'direccion' => 'AVENIDA PRINCIPAL C/C ALFREDO JAHN Y ÁLVAREZ MICHAUD, CASA COLEGIO DE BIOANALISTAS, N° 13-01, URBANIZACIóN LOS CHORROS.',
                'telefono' => '2122396072',
                'resumen' => 'REVISTA ARBITRADA E INDIZADA DEDICADA A PUBLICAR LOS TRABAJOS DE LOS PROFESIONALES DEL BIOANáLISIS EN INVESTIGACIóN BáSICA Y APLICADA.',
                'portada' => '[{"name":"portadas\\/Acta Cient__fica_dwc3i0mv.jpg","usrName":"Acta Científica.jpg","size":43080,"type":"image\\/jpeg","thumbnail":"portadas\\/thActa Cient__fica_pb77dpp7.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":2887,"searchStr":"Acta Científica.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            9 => 
            array (
                'id' => 13,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ACTA MICROSCóPICA',
                'correo_revista' => 'principal@mcaetano.dev',
                'editorial_id' => 24,
                'periodicidad_id' => 8,
                'formato_id' => 3,
                'estado_id' => 14,
                'ciudad_id' => 279,
                'nombres_editor' => 'GEMA',
                'apellidos_editor' => 'GONZáLEZ',
                'correo_editor' => '',
                'deposito_legal_impreso' => 'pp 92-0073',
                'deposito_legal_digital' => '321',
                'issn_impreso' => '0798-454',
                'issn_digital' => '2224-892',
                'url' => ' https://acta-microscopica.org/acta',
                'anio_inicial' => 1992,
                'direccion' => 'CARRETERA PANAMERICANA, KM 11, ALTOS DE PIPE, ESTADO MIRANDA',
                'telefono' => '2122396072',
            'resumen' => 'ACTA MICROSCóPICA ES LA REVISTA OFICIAL DEL CIASEM ( COMITé INTERAMERICANO DE SOCIEDADES DE MICROSCOPíA ELECTRóNICA) . ESTA REVISTA ES UN FORO INTERNACIONAL, ABIERTO A TODOS LOS CIENTíFICOS Y TECNóLOGOS QUE UTILIZAN CUALQUIER FORMA DE MICROSCOPíA, MICROSCOPíA ELECTRóNICA, NUEVA MICROSCOPíA DE SONDA DE BARRIDO Y TAMBIéN MICROSCOPíA CONFOCAL Y óPTICA PARA APLICACIONES EN FíSICA, QUíMICA, MATERIALES Y CIENCIAS BIOLóGICAS, PARA PUBLICAR SUS INVESTIGACIONES.',
                'portada' => '[{"name":"portadas\\/Acta Microsc__pica_j58eluos.jpg","usrName":"Acta Microscópica.jpg","size":46023,"type":"image\\/jpeg","thumbnail":"portadas\\/thActa Microsc__pica_284kehxu.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3758,"searchStr":"Acta Microscópica.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ARA MACAO',
                'correo_revista' => 'revista.aramacao@gmail.c',
                'editorial_id' => 22,
                'periodicidad_id' => 7,
                'formato_id' => 1,
                'estado_id' => 24,
                'ciudad_id' => 149,
                'nombres_editor' => 'SERGIO',
                'apellidos_editor' => 'TEIJERO',
                'correo_editor' => '',
                'deposito_legal_impreso' => 'dc2020000158',
                'deposito_legal_digital' => '153',
                'issn_impreso' => '2665-025',
                'issn_digital' => '987',
                'url' => '',
                'anio_inicial' => 2018,
                'direccion' => 'URB. LOS PALOS GRANDES',
                'telefono' => '4166335561',
                'resumen' => 'REVISTA CIENTíFICO COMUNITARIA CREADA PARA DIFUNDIR LA PRODUCCIóN CIENTíFICA DE LAS INSTITUCIONES ACADéMICAS E INVESTIGATIVAS, LOS CONSEJOS COMUNALES, LAS COMUNAS, LOS MOVIMIENTOS SOCIALES Y LAS DEMáS COMUNIDADES DE LA REPúBLICA BOLIVARIANA DE VENEZUELA, PARA LAS CIUDADANAS Y CIUDADANOS DEL MUNDO AMANTES DE LA PAZ Y LA SOLIDARIDAD ENTRE LOS PUEBLOS Y EN APOYO A LA POLíTICA DE PUNTO Y CíRCULO CREADA POR EL COMANDANTE HUGO CHáVEZ FRíAS.',
                'portada' => '[{"name":"portadas\\/Ara Macao_negeogzf.jpg","usrName":"Ara Macao.jpg","size":16751,"type":"image\\/jpeg","thumbnail":"portadas\\/thAra Macao_wi18d8ds.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":2659,"searchStr":"Ara Macao.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            11 => 
            array (
                'id' => 14,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'AKADEMOS',
                'correo_revista' => 'saberucvrevistas@gmail.co',
                'editorial_id' => 23,
                'periodicidad_id' => 8,
                'formato_id' => 1,
                'estado_id' => 24,
                'ciudad_id' => 149,
                'nombres_editor' => 'MARíA',
                'apellidos_editor' => 'MARTíNEZ PADRóN',
                'correo_editor' => 'catuloster@gmail.com',
                'deposito_legal_impreso' => '987',
                'deposito_legal_digital' => '426',
                'issn_impreso' => '1317-179',
                'issn_digital' => '654',
                'url' => 'http://saber.ucv.ve/ojs/index.php/rev_ak/issue/arc',
                'anio_inicial' => 1999,
                'direccion' => 'AVENIDA NEVERí CON CALLE EDISON, CENTRO COMERCIAL LOS CHAGUARAMOS. PISO 1. APARTADO POSTAL 47972, LOS CHAGUARAMOS.',
                'telefono' => '212 6050326',
            'resumen' => 'LA POLíTICA EDITORIAL DE LA REVISTA PRETENDE REFLEJAR LA PLURALIDAD DE INTERESES DE LAS DIFERENTES áREAS DEL POSTGRADO, DANDO CABIDA EN SUS PáGINAS A LAS CONTRIBUCIONES PROCEDENTES DE LOS CAMPOS DE CONOCIMIENTOS INHERENTES A LA ACTIVIDAD DE ESAS TAREAS, ENTRE LOS QUE SE CUENTAN LOS DE POLíTICA EDUCATIVA, REFLEXIóN FILOSóFICA, CRíTICA LITERARIA, PRAGMáTICA, ANáLISIS DEL DISCURSO, LINGüíSTICA APLICADA (A LA ENSEñANZA DEL ESPAñOL O DE IDIOMAS EXTRANJEROS, AL TRATAMIENTO LINGüíSTICO DE PROBLEMAS LITERARIOS); ADQUISICIóN DE LA LENGUA, HALLAZGOS HISTóRICOS, INVESTIGACIONES EN LAS áREAS DE LA GEOGRAFíA, LA PSICOLOGíA, ENTRE OTROS.',
                'portada' => '[{"name":"portadas\\/Akademos_s3v6jgvl.jpg","usrName":"Akademos.jpg","size":16935,"type":"image\\/jpeg","thumbnail":"portadas\\/thAkademos_xdnxj1ym.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":2606,"searchStr":"Akademos.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            12 => 
            array (
                'id' => 15,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ALCANCE',
                'correo_revista' => 'revistaagronomiaucv@gmail',
                'editorial_id' => 23,
                'periodicidad_id' => 9,
                'formato_id' => 3,
                'estado_id' => 4,
                'ciudad_id' => 64,
                'nombres_editor' => 'DAYANA ',
                'apellidos_editor' => 'PéREZ',
                'correo_editor' => 'dayanaperez@gmail.com',
                'deposito_legal_impreso' => '654',
                'deposito_legal_digital' => '486',
                'issn_impreso' => '0041-828',
                'issn_digital' => '1856-557',
                'url' => 'http://saber.ucv.ve/ojs/index.php/rev_agro/issue/v',
                'anio_inicial' => 1956,
                'direccion' => 'FACULTAD DE AGRONOMíA, U.C.V.',
                'telefono' => '4143439007 ',
                'resumen' => 'LA REVISTA ALCANCE DE LA FACULTAD DE AGRONOMíA DE LA UNIVERSIDAD CENTRAL DE VENEZUELA CONSTITUYE EL óRGANO DIVULGATIVO DESTINADO A DIFUNDIR CONOCIMIENTOS CIENTíFICOS Y TECNOLóGICOS INéDITOS EN EL áREA DE LAS CIENCIAS AGRíCOLAS EN EL MEDIO TROPICAL, CON EL PROPóSITO DE CONTRIBUIR CON LA PROYECCIóN SOCIAL DEL CONOCIMIENTO COMO ESTRATEGIA PARA SATISFACER LAS NECESIDADES AGROALIMENTARIAS Y AMBIENTALES DE LAS GENERACIONES PRESENTES Y FUTURAS.',
                'portada' => '[{"name":"portadas\\/Alcance_7t0f8iq5.jpg","usrName":"Alcance.jpg","size":20235,"type":"image\\/jpeg","thumbnail":"portadas\\/thAlcance_07fvjsbg.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":2545,"searchStr":"Alcance.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            13 => 
            array (
                'id' => 16,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ÁGORA TáCTICA',
                'correo_revista' => 'hormiguero.umbv@gmail.com',
                'editorial_id' => 25,
                'periodicidad_id' => 9,
                'formato_id' => 1,
                'estado_id' => 24,
                'ciudad_id' => 149,
                'nombres_editor' => '',
                'apellidos_editor' => '',
                'correo_editor' => '',
                'deposito_legal_impreso' => 'dc2022001954',
                'deposito_legal_digital' => '759',
                'issn_impreso' => '654',
                'issn_digital' => '321',
                'url' => 'https://www.hormiguero.com.ve/agora/',
                'anio_inicial' => 2022,
                'direccion' => 'RECTORADO DE LA UNIVERSIDAD MILITAR
BOLIVARIANA DE VENEZUELA      AV. LAS ESCUELAS ENTRE CALLES 14 Y 15. CóDIGO POSTAL 
FUERTE TIUNA, EL VALLE.',
                'telefono' => '02128086205',
                'resumen' => 'ÁGORA TáCTICA, ES UNA REVISTA ARBITRADA DE CIENCIAS Y ARTES MILITARES DEL CENTRO DE ESTUDIOS DE POSTGRADO TáCTICOS, TéCNICOS Y LOGíSTICOS, ADSCRITO A LA UNIVERSIDAD MILITAR BOLIVARIANA DE VENEZUELA. LA CUAL REúNE LOS PRODUCTOS INTELECTUALES ACADéMICOS DE LOS PROFESIONALES MILITARES Y NO MILITARES REALIZADOS EN EL CENTRO DE
ESTUDIOS DE POSTGRADO TáCTICOS, TéCNICOS Y LOGíSTICOS (CEPTTL),
DE LA UNIVERSIDAD MILITAR BOLIVARIANA DE VENEZUELA, CUYA MISIóN ES FORMAR Y CAPACITAR A LOS OFICIALES DE LA FUERZA ARMADA NACIONAL BOLIVARIANA, EN EL NIVEL TáCTICO DE LA PLANIFICACIóN.',
            'portada' => '[{"name":"portadas\\/gora (2) (1)_cnyidb38.jpg","usrName":"gora (2) (1).jpg","size":42145,"type":"image\\/jpeg","thumbnail":"portadas\\/thgora (2) (1)_sc0yrfn5.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3026,"searchStr":"gora (2) (1).jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            14 => 
            array (
                'id' => 17,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ALDEA MUNDO',
                'correo_revista' => 'info@saber.ula',
                'editorial_id' => 20,
                'periodicidad_id' => 8,
                'formato_id' => 3,
                'estado_id' => 19,
                'ciudad_id' => 405,
                'nombres_editor' => 'FRANCISCO',
                'apellidos_editor' => 'SáNCHEZ CHACóN',
                'correo_editor' => 'aldeamundo@gmail.com',
                'deposito_legal_impreso' => '1996-02ta-3',
                'deposito_legal_digital' => 'ppi201402ta4545',
                'issn_impreso' => '1316-672',
                'issn_digital' => '2443-451',
                'url' => 'http://erevistas.saber.ula.ve/index.php/aldeamundo',
                'anio_inicial' => 1996,
                'direccion' => 'UNIVERSIDAD DE LOS ANDES,
CENTRO DE ESTUDIOS DE FRONTERAS E INTEGRACIóN (CEFI),
EDIFICIO ADMINISTRATIVO, 3ER. PISO,
AV. UNIVERSIDAD, SECTOR PARAMILLO.
',
                'telefono' => '2742524192',
            'resumen' => 'ALDEA MUNDO ES UNA PUBLICACIóN CIENTíFICA SEMESTRAL AUSPICIADA POR EL CENTRO DE ESTUDIOS DE FRONTERAS E INTEGRACIóN (CEFI) “DR. JOSé MANUEL BRICEñO MONZILLO” DE LA UNIVERSIDAD DE LOS ANDES-TáCHIRA, NúCLEO UNIVERSITARIO “DR. PEDRO RINCóN GUTIéRREZ” Y EL CONSEJO DE DESARROLLO, CIENTíFICO, HUMANíSTICO, TECNOLóGICO Y DE LAS ARTES (CDCHTA) DE LA UNIVERSIDAD DE LOS ANDES. EL CEFI CUENTA CON MáS DE 35 AñOS DE EXISTENCIA DEDICADO A LA INVESTIGACIóN DE LAS TEMáTICAS DE FRONTERAS INTERNACIONALES E INTEGRACIóN REGIONAL EN LOS áMBITOS LOCAL, NACIONAL E INTERNACIONAL. DE ALLí SURGE ALDEA MUNDO CON LOS OBJETIVOS DE DIVULGACIóN DE CONOCIMIENTOS SOBRE FRONTERAS, INTEGRACIóN REGIONAL, GEOPOLíTICA Y GLOBALIZACIóN DESDE DISTINTAS DISCIPLINAS DE LAS CIENCIAS SOCIALES Y EN LOS DISTINTOS áMBITOS GEOGRáFICOS.',
                'portada' => '[{"name":"portadas\\/Aldea Mundo_pe4cd2ru.jpg","usrName":"Aldea Mundo.jpg","size":38076,"type":"image\\/jpeg","thumbnail":"portadas\\/thAldea Mundo_qaa7mkn5.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3544,"searchStr":"Aldea Mundo.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            15 => 
            array (
                'id' => 18,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'AGROECOLOGíA GLOBAL',
                'correo_revista' => 'fundakoinonia@gmail.com',
                'editorial_id' => 26,
                'periodicidad_id' => 8,
                'formato_id' => 1,
                'estado_id' => 10,
                'ciudad_id' => 158,
                'nombres_editor' => 'JORGE',
                'apellidos_editor' => 'CORONEL PIñA',
                'correo_editor' => 'koinonia@fundacionkoinoni',
                'deposito_legal_impreso' => 'fa2019000051',
                'deposito_legal_digital' => '369',
                'issn_impreso' => '2665-029',
                'issn_digital' => '147',
                'url' => '',
                'anio_inicial' => 2019,
                'direccion' => 'CALLE B ENTRE CALLE 1 Y CALLE 2. CASA NRO. PA-42.
URBANIZACIóN. VIRGEN MORENITA. LAS CASITAS
',
                'telefono' => '4143911451',
                'resumen' => ' REVISTA ARBITRADA ELECTRóNICA DEL áREA CIENCIAS DEL AGRO Y DEL MAR, ADSCRITA A LA FUNDACIóN KOINONíA ES UNA PUBLICACIóN DE APARICIóN SEMESTRAL, DIRIGIDA A INVESTIGADORES, DOCENTES, ESTUDIANTES DE PRE Y POSGRADO; QUE DIVULGA RESULTADOS DE INVESTIGACIONES, CONOCIMIENTOS ORIGINALES, NOTAS CIENTIFICAS, COMUNICACIONES BREVES Y REVISIONES RELACIONADOS CON LA AGROECOLOGíA, AGROALIMENTACIóN, TECNOLOGíA DE ALIMENTOS, CIENCIAS AGROGENóMICAS, CIENCIAS AMBIENTALES, CIENCIAS AGROPECUARIAS Y FORESTALES, CIENCIAS VETERINARIAS, CIENCIAS DEL MAR, INGENIERíA PESQUERA, ORIGINALES E INéDITOS.',
                'portada' => '[{"name":"portadas\\/Agroecolog__a Global_j61z3gwk.jpg","usrName":"Agroecología Global.jpg","size":47371,"type":"image\\/jpeg","thumbnail":"portadas\\/thAgroecolog__a Global_1kn9iysa.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4207,"searchStr":"Agroecología Global.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            16 => 
            array (
                'id' => 19,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'AGROINDUSTRIA, SOCIEDAD Y AMBIENTE',
                'correo_revista' => 'mireyavaldez@ucla.edu.ve',
                'editorial_id' => 27,
                'periodicidad_id' => 8,
                'formato_id' => 2,
                'estado_id' => 12,
                'ciudad_id' => 212,
                'nombres_editor' => 'MIREYA',
                'apellidos_editor' => 'VALDEZ D',
                'correo_editor' => 'mireyavaldez@ucla.edu.ve',
                'deposito_legal_impreso' => '321',
                'deposito_legal_digital' => 'ppl201302la4406',
                'issn_impreso' => '321',
                'issn_digital' => '2343-611',
                'url' => 'https://revistas.uclave.org/index.php/asa/about',
                'anio_inicial' => 2013,
                'direccion' => 'AVENIDA LAS INDUSTRIAS. NúCLEO OBELISCO. PROGRAMA DE INGENIERíA AGROINDUSTRIAL.',
                'telefono' => '58 25125916',
                'resumen' => 'REVISTA CIENTíFICA DE ACCESO ABIERTO, MULTIDISCIPLINARIA EN TEMAS PRIORITARIOS DE AGROINDUSTRIA, SISTEMAS PRODUCTIVOS, TECNOLOGíA DE PRODUCTOS DE ORIGEN VEGETAL Y ANIMAL.',
                'portada' => '[{"name":"portadas\\/011. Agroindustria, Sociedad y Ambiente_33onbqjg.jpg","usrName":"011. Agroindustria, Sociedad y Ambiente.jpg","size":46250,"type":"image\\/jpeg","thumbnail":"portadas\\/th011. Agroindustria, Sociedad y Ambiente_zbszge5h.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":4129,"searchStr":"011. Agroindustria, Sociedad y Ambiente.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            17 => 
            array (
                'id' => 20,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'UNIVERSIDAD MILITAR DE VENEZUELA',
                'correo_revista' => 'hormiguero.umbv@gmail.com',
                'editorial_id' => 28,
                'periodicidad_id' => 9,
                'formato_id' => 3,
                'estado_id' => 24,
                'ciudad_id' => 149,
                'nombres_editor' => 'EDITORIAL HORMIGUERO',
                'apellidos_editor' => '',
                'correo_editor' => 'hormiguero.umbv@gmail.com',
                'deposito_legal_impreso' => '147',
                'deposito_legal_digital' => 'pp2000602dc2263',
                'issn_impreso' => '1856-993',
                'issn_digital' => '1856-993',
                'url' => 'https://www.hormiguero.com.ve/download/revista-arb',
                'anio_inicial' => 2009,
                'direccion' => 'UNIVERSIDAD MILITAR BOLIVARIANA DE VENEZUELA AV. LAS ESCUELAS ENTRE CALLES 14 Y 15. CóDIGO POSTAL 
FUERTE TIUNA, EL VALLE   ',
                'telefono' => '0212',
                'resumen' => 'LA REVISTA PUBLICA ARTíCULOS RELACIONADOS CON LA CIENCIA Y ARTE MILITARES, ESTRATEGIA, GEOPOLíTICA, PROCESOS SOCIOPOLíTICOS VENEZOLANOS, RELACIONES INTERNACIONALES, EDUCACIóN MILITAR.',
                'portada' => '[{"name":"portadas\\/021. Columnata_eihzfo2d.jpg","usrName":"021. Columnata.jpg","size":37552,"type":"image\\/jpeg","thumbnail":"portadas\\/th021. Columnata_65zqhbhy.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":2899,"searchStr":"021. Columnata.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
            18 => 
            array (
                'id' => 21,
                'area_conocimiento_id' => 1,
                'indices_id' => 1,
                'lenguajes_id' => 1,
                'revista' => 'ANUARIO DE DERECHO',
                'correo_revista' => 'anuarioderechoula@ula.ve',
                'editorial_id' => 20,
                'periodicidad_id' => 9,
                'formato_id' => 2,
                'estado_id' => 13,
                'ciudad_id' => 245,
                'nombres_editor' => 'CENTRO DE INVESTIGAC',
                'apellidos_editor' => '',
                'correo_editor' => '',
                'deposito_legal_impreso' => '258',
                'deposito_legal_digital' => ' pp. 106908me33',
                'issn_impreso' => '147',
                'issn_digital' => '0076-655',
                'url' => 'www.saber.ula.ve/anuarioderecho/',
                'anio_inicial' => 1969,
                'direccion' => 'CENTRO DE INVESTIGACIONES JURíDICAS
AV. LAS AMéRICAS. CONJUNTO LA LIRIA.',
                'telefono' => '02742402652',
                'resumen' => ' DESPLIEGA SU LABOR MEDIANTE LA PUBLICACIóN DE ARTíCULOS ORIGINALES, ESTUDIOS COMPARATIVOS, PROYECTOS DE LEYES, ANáLISIS DE LEYES, ORíGENES DE LEYES, PONENCIAS Y RESEñAS EN EL áMBITO DE LAS CIENCIAS SOCIALES Y AFINES.',
                'portada' => '[{"name":"portadas\\/016. Anuario de Derecho_igs3ok8g.jpg","usrName":"016. Anuario de Derecho.jpg","size":32423,"type":"image\\/jpeg","thumbnail":"portadas\\/th016. Anuario de Derecho_bfihhtog.jpg","thumbnail_type":"image\\/jpeg","thumbnail_size":3562,"searchStr":"016. Anuario de Derecho.jpg,!:sStrEnd"}]',
                'usuario_id' => 1,
            ),
        ));
        
        
    }
}